# Generated by Django 6.0.5 on 2026-05-14 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='cover_caption',
            field=models.CharField(blank=True, max_length=300, verbose_name='Подпись к обложке'),
        ),
        migrations.AddField(
            model_name='article',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='articles/', verbose_name='Обложка статьи'),
        ),
        migrations.AddField(
            model_name='category',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='Обложка рубрики'),
        ),
    ]
