# Generated by Django 6.0.5 on 2026-05-14 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_article_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_editor_pick',
            field=models.BooleanField(default=False, verbose_name='Editor’s pick'),
        ),
    ]
