# Generated by Django 6.0.5 on 2026-05-14 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_article_is_editor_pick'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='issue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='core.issue', verbose_name='Issue'),
        ),
        migrations.AddField(
            model_name='article',
            name='issue_order',
            field=models.PositiveIntegerField(default=100, verbose_name='Issue order'),
        ),
    ]
