# Generated by Django 6.0.5 on 2026-08-24 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_article_issue_article_issue_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='articles/gallery/', verbose_name='Image')),
                ('caption', models.CharField(blank=True, max_length=300, verbose_name='Caption')),
                ('order', models.PositiveIntegerField(default=100, verbose_name='Order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='articles.article', verbose_name='Article')),
            ],
            options={
                'verbose_name': 'Article image',
                'verbose_name_plural': 'Article images',
                'ordering': ['order', 'id'],
            },
        ),
    ]
