# Generated by Django 6.0.5 on 2026-05-14 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_current', models.BooleanField(default=False, verbose_name='Current issue')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='issues/', verbose_name='Issue cover image')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Publication date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Issue',
                'verbose_name_plural': 'Issues',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IssueTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('ru', 'Russian'), ('en', 'English'), ('lt', 'Lithuanian')], max_length=2, verbose_name='Language')),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
                ('slug', models.SlugField(max_length=260, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='core.issue', verbose_name='Issue')),
            ],
            options={
                'verbose_name': 'Issue translation',
                'verbose_name_plural': 'Issue translations',
                'unique_together': {('issue', 'language'), ('language', 'slug')},
            },
        ),
    ]
